### ISSUE TITLE
Are you tired?

### ISSUE THREAD

**Issue by entraptaa** [xtreameprogram/MusicBotTut#4]
Bruh there are a lot of typos in your source code like wtf

**Comment by MrJacz** [comment]
The typos are on purpose to reduce the amount of copy pasta's

**Comment by xtreameprogram** [comment]
What Jacz said. We don't encourage people just taking someone else's work. This is to help people to learn how to make this. Not just give it to them

**Comment by AsP3X** [comment]
Yeah that's correct but making mistakes in a let's say template is not a great method.

So remove this repro or make it private if you have problems with sharing your work to a open source platform.

**Comment by MrJacz** [comment]
Lmfao no, We have no problem with anything.
This isn't a template
This is simply the src of a youtube video tutorial

**Comment by xtreameprogram** [comment]
What jacz said. This is the supplemental code to follow along the video to. The purpose was to be educational. You can't learn if you just take something without studying it. If you take this and study it, you will find simple mistakes and be able to learn it in the process
