### ISSUE TITLE
This is not going to work

### ISSUE THREAD

**Issue by AsP3X** [xtreameprogram/MusicBotTut#5]
Please correct the spelling mistakes so that we don't have to correct it by our self.
This is pain in the back side to correct all of these.

**Comment by MrJacz** [comment]
This is simply the src of a youtube video tutorial that isn't fully correct because you're not supposed to copy it you're supposed to watch the youtube tutorial like everyone else

**Comment by xtreameprogram** [comment]
Zomby, if you look at the git history, you will find a perfectly working version. This is just to prevent people who are only interested in taking it and then coming asking for us to do the work for them. I did have a fully working version up. But, people kept coming and asking for us to do all the work for them.
